[theme]
name = "bearded-void"
description = "Bearded Theme Void palette adapted from JSON/Zed style for Netherize Editor runtime themes"

[editor]
bg = "#171322"
fg = "#c7bfdb"
cursor = "#7A63ED"
selection = "#221c32"
gutter = "#171322"
gutter_active = "#7e6dad"

[ui]
bg = "#120f1b"
sidebar_bg = "#171322"
panel_bg = "#171322"
terminal_bg = "#171322"
overlay_bg = "#120f1bD9"
status_bar_bg = "#120f1b"
border_color = "#0a080e"
selection_bg = "#28213c"

fg = "#c7bfdb"
fg_dim = "#aa9fc8"
fg_ghost = "#4f4273"

accent = "#7A63ED"
cyan = "#89C4FF"
magenta = "#A8547A"
amber = "#585785"
success = "#14b871"
warning = "#cc8c39"
info = "#7A63ED"
error = "#C13838"

mode_normal = "#7A63ED"
mode_insert = "#14b871"
mode_visual = "#A8547A"

top_bar_height = 36.0

[git]
modified_sidebar = "#04c4d9"
added_sidebar = "#14b871"
modified_gutter = "#04c4d9"
added_gutter = "#14b871"
deleted_gutter = "#C13838"
status_bar_height = 32.0

[syntax]
keyword = "#585785"
string = "#6DBBFF"
function = "#7A63ED"
comment = "#4f4273"
type = "#2BD3E2"
number = "#C13838"
identifier = "#c7bfdb"
parameter = "#A8547A"
field = "#c7bfdb"
property = "#c7bfdb"
constant = "#C13838"
operator = "#585785"
punctuation = "#c7bfdb66"
macro = "#7A63ED"
lifetime = "#3D8DE2"
boolean = "#C13838"
escape = "#3D8DE2"
variable = "#D65170"
constructor = "#2C729E"
attribute = "#A8547A"
namespace = "#2BD3E2"
tag = "#7A63ED"
keyword_control = "#585785"
keyword_storage = "#89C4FF"
string_escape = "#3D8DE2"
function_builtin = "#7A63ED"
comment_doc = "#4f4273"
type_builtin = "#2BD3E2"
variable_builtin = "#D65170"
markup_strong = "#D65170"
markup_italic = "#3D8DE2"
markup_inline_code = "#2BD3E2"
markup_link = "#7A63ED"

