[theme]
name = "bearded-milkshake-blueberry"
description = "Bearded Theme Milkshake Blueberry palette adapted from JSON/Zed style for Netherize Editor runtime themes"

[editor]
bg = "#dad9eb"
fg = "#07060c"
cursor = "#422eb0"
selection = "#c6c5e0"
gutter = "#dad9eb"
gutter_active = "#3e3b71"

[ui]
bg = "#cfcde5"
sidebar_bg = "#dad9eb"
panel_bg = "#dad9eb"
terminal_bg = "#dad9eb"
overlay_bg = "#cfcde5D9"
status_bar_bg = "#cfcde5"
border_color = "#a9a7d1"
selection_bg = "#afabd4"

fg = "#07060c"
fg_dim = "#000000"
fg_ghost = "#8886bf"

accent = "#422eb0"
cyan = "#008f8f"
magenta = "#c121a4"
amber = "#c08403"
success = "#008b17"
warning = "#c08403"
info = "#0076c5"
error = "#d12525"

mode_normal = "#422eb0"
mode_insert = "#008b17"
mode_visual = "#c121a4"

top_bar_height = 36.0

[git]
modified_sidebar = "#0076c5"
added_sidebar = "#008b17"
modified_gutter = "#0076c5"
added_gutter = "#008b17"
deleted_gutter = "#d12525"
status_bar_height = 32.0

[syntax]
keyword = "#c08403"
string = "#008b17"
function = "#0076c5"
comment = "#747187"
type = "#7522d3"
number = "#d12525"
identifier = "#07060c"
parameter = "#c121a4"
field = "#07060c"
property = "#07060c"
constant = "#d12525"
operator = "#c08403"
punctuation = "#07060c"
macro = "#0076c5"
lifetime = "#b96000"
boolean = "#d12525"
escape = "#b96000"
variable = "#da2a5f"
constructor = "#668b07"
attribute = "#c121a4"
namespace = "#7522d3"
tag = "#0076c5"
keyword_control = "#c08403"
keyword_storage = "#008f8f"
string_escape = "#b96000"
function_builtin = "#0076c5"
comment_doc = "#747187"
type_builtin = "#7522d3"
variable_builtin = "#da2a5f"
markup_strong = "#da2a5f"
markup_italic = "#b96000"
markup_inline_code = "#7522d3"
markup_link = "#0076c5"

