[theme]
name = "bearded-milkshake-raspberry"
description = "Bearded Theme Milkshake Raspberry palette adapted from JSON/Zed style for Netherize Editor runtime themes"

[editor]
bg = "#f1e8eb"
fg = "#15070b"
cursor = "#d1174f"
selection = "#e5d5da"
gutter = "#f1e8eb"
gutter_active = "#784859"

[ui]
bg = "#eadde1"
sidebar_bg = "#f1e8eb"
panel_bg = "#f1e8eb"
terminal_bg = "#f1e8eb"
overlay_bg = "#eadde1D9"
status_bar_bg = "#eadde1"
border_color = "#d4b8c2"
selection_bg = "#d7bdc5"

fg = "#15070b"
fg_dim = "#000000"
fg_ghost = "#c198a7"

accent = "#d1174f"
cyan = "#008f8f"
magenta = "#c121a4"
amber = "#c08403"
success = "#008b17"
warning = "#c08403"
info = "#0076c5"
error = "#d12525"

mode_normal = "#d1174f"
mode_insert = "#008b17"
mode_visual = "#c121a4"

top_bar_height = 36.0

[git]
modified_sidebar = "#0076c5"
added_sidebar = "#008b17"
modified_gutter = "#0076c5"
added_gutter = "#008b17"
deleted_gutter = "#d12525"
status_bar_height = 32.0

[syntax]
keyword = "#c08403"
string = "#008b17"
function = "#0076c5"
comment = "#a75b72"
type = "#7522d3"
number = "#d12525"
identifier = "#15070b"
parameter = "#c121a4"
field = "#15070b"
property = "#15070b"
constant = "#d12525"
operator = "#c08403"
punctuation = "#15070b"
macro = "#0076c5"
lifetime = "#b96000"
boolean = "#d12525"
escape = "#b96000"
variable = "#da2a5f"
constructor = "#668b07"
attribute = "#c121a4"
namespace = "#7522d3"
tag = "#0076c5"
keyword_control = "#c08403"
keyword_storage = "#008f8f"
string_escape = "#b96000"
function_builtin = "#0076c5"
comment_doc = "#a75b72"
type_builtin = "#7522d3"
variable_builtin = "#da2a5f"
markup_strong = "#da2a5f"
markup_italic = "#b96000"
markup_inline_code = "#7522d3"
markup_link = "#0076c5"

