[theme]
name = "bearded-feat-melle-julie-light"
description = "Bearded Theme feat. Melle Julie Light palette adapted from JSON/Zed style for Netherize Editor runtime themes"

[editor]
bg = "#edeeee"
fg = "#000000"
cursor = "#218d8f"
selection = "#dddfdf"
gutter = "#edeeee"
gutter_active = "#5f6464"

[ui]
bg = "#e4e5e5"
sidebar_bg = "#edeeee"
panel_bg = "#edeeee"
terminal_bg = "#edeeee"
overlay_bg = "#e4e5e5D9"
status_bar_bg = "#e4e5e5"
border_color = "#c6c9c9"
selection_bg = "#cacccc"

fg = "#000000"
fg_dim = "#000000"
fg_ghost = "#acb0b0"

accent = "#218d8f"
cyan = "#23716d"
magenta = "#ae6cbe"
amber = "#b48806"
success = "#2aa54d"
warning = "#c97a2a"
info = "#1f89cf"
error = "#d24545"

mode_normal = "#218d8f"
mode_insert = "#2aa54d"
mode_visual = "#ae6cbe"

top_bar_height = 36.0

[git]
modified_sidebar = "#1f89cf"
added_sidebar = "#2aa54d"
modified_gutter = "#1f89cf"
added_gutter = "#2aa54d"
deleted_gutter = "#d24545"
status_bar_height = 32.0

[syntax]
keyword = "#b48806"
string = "#2aa54d"
function = "#1f89cf"
comment = "#577172"
type = "#7c68ef"
number = "#d24545"
identifier = "#000000"
parameter = "#ae6cbe"
field = "#000000"
property = "#000000"
constant = "#d24545"
operator = "#b48806"
punctuation = "#00000066"
macro = "#1f89cf"
lifetime = "#c97a2a"
boolean = "#d24545"
escape = "#c97a2a"
variable = "#39a9b4"
constructor = "#81a622"
attribute = "#ae6cbe"
namespace = "#7c68ef"
tag = "#1f89cf"
keyword_control = "#b48806"
keyword_storage = "#23716d"
string_escape = "#c97a2a"
function_builtin = "#1f89cf"
comment_doc = "#577172"
type_builtin = "#7c68ef"
variable_builtin = "#39a9b4"
markup_strong = "#39a9b4"
markup_italic = "#c97a2a"
markup_inline_code = "#7c68ef"
markup_link = "#1f89cf"

