[theme]
name = "bearded-oceanic"
description = "Bearded Theme Oceanic palette adapted from JSON/Zed style for Netherize Editor runtime themes"

[editor]
bg = "#1a2b34"
fg = "#cddde6"
cursor = "#97c892"
selection = "#233945"
gutter = "#1a2b34"
gutter_active = "#78a4bc"

[ui]
bg = "#16252d"
sidebar_bg = "#1a2b34"
panel_bg = "#1a2b34"
terminal_bg = "#1a2b34"
overlay_bg = "#16252dD9"
status_bar_bg = "#16252d"
border_color = "#101a20"
selection_bg = "#27414f"

fg = "#cddde6"
fg_dim = "#acc6d4"
fg_ghost = "#467188"

accent = "#97c892"
cyan = "#59c6c8"
magenta = "#d194cd"
amber = "#f6cc73"
success = "#97c892"
warning = "#DC8255"
info = "#5fb2df"
error = "#ee5d75"

mode_normal = "#97c892"
mode_insert = "#97c892"
mode_visual = "#d194cd"

top_bar_height = 36.0

[git]
modified_sidebar = "#5fb2df"
added_sidebar = "#97c892"
modified_gutter = "#5fb2df"
added_gutter = "#97c892"
deleted_gutter = "#ee5d75"
status_bar_height = 32.0

[syntax]
keyword = "#f6cc73"
string = "#97c892"
function = "#5fb2df"
comment = "#467188"
type = "#978dd6"
number = "#B4552D"
identifier = "#cddde6"
parameter = "#d194cd"
field = "#cddde6"
property = "#cddde6"
constant = "#B4552D"
operator = "#f6cc73"
punctuation = "#cddde666"
macro = "#5fb2df"
lifetime = "#DC8255"
boolean = "#B4552D"
escape = "#DC8255"
variable = "#ee5d75"
constructor = "#A4EF58"
attribute = "#d194cd"
namespace = "#978dd6"
tag = "#5fb2df"
keyword_control = "#f6cc73"
keyword_storage = "#59c6c8"
string_escape = "#DC8255"
function_builtin = "#5fb2df"
comment_doc = "#467188"
type_builtin = "#978dd6"
variable_builtin = "#ee5d75"
markup_strong = "#ee5d75"
markup_italic = "#DC8255"
markup_inline_code = "#978dd6"
markup_link = "#5fb2df"

