[theme]
name = "bearded-milkshake-vanilla-banana"
description = "Bearded Theme Milkshake Vanilla Banana palette adapted from JSON/Zed style for Netherize Editor runtime themes"

[editor]
bg = "#ece7da"
fg = "#000000"
cursor = "#937416"
selection = "#e2dac6"
gutter = "#ece7da"
gutter_active = "#72633b"

[ui]
bg = "#e6dfce"
sidebar_bg = "#ece7da"
panel_bg = "#ece7da"
terminal_bg = "#ece7da"
overlay_bg = "#e6dfceD9"
status_bar_bg = "#e6dfce"
border_color = "#d2c6a7"
selection_bg = "#d5c9ac"

fg = "#000000"
fg_dim = "#000000"
fg_ghost = "#c1b085"

accent = "#937416"
cyan = "#008f8f"
magenta = "#c121a4"
amber = "#c08403"
success = "#008b17"
warning = "#c08403"
info = "#0076c5"
error = "#d12525"

mode_normal = "#937416"
mode_insert = "#008b17"
mode_visual = "#c121a4"

top_bar_height = 36.0

[git]
modified_sidebar = "#0076c5"
added_sidebar = "#008b17"
modified_gutter = "#0076c5"
added_gutter = "#008b17"
deleted_gutter = "#d12525"
status_bar_height = 32.0

[syntax]
keyword = "#c08403"
string = "#008b17"
function = "#0076c5"
comment = "#796d49"
type = "#7522d3"
number = "#d12525"
identifier = "#000000"
parameter = "#c121a4"
field = "#000000"
property = "#000000"
constant = "#d12525"
operator = "#c08403"
punctuation = "#000000"
macro = "#0076c5"
lifetime = "#b96000"
boolean = "#d12525"
escape = "#b96000"
variable = "#da2a5f"
constructor = "#668b07"
attribute = "#c121a4"
namespace = "#7522d3"
tag = "#0076c5"
keyword_control = "#c08403"
keyword_storage = "#008f8f"
string_escape = "#b96000"
function_builtin = "#0076c5"
comment_doc = "#796d49"
type_builtin = "#7522d3"
variable_builtin = "#da2a5f"
markup_strong = "#da2a5f"
markup_italic = "#b96000"
markup_inline_code = "#7522d3"
markup_link = "#0076c5"

