[theme]
name = "bearded-earth"
description = "Bearded Theme Earth palette adapted from JSON/Zed style for Netherize Editor runtime themes"

[editor]
bg = "#221b1b"
fg = "#caa5a5"
cursor = "#d35386"
selection = "#302626"
gutter = "#221b1b"
gutter_active = "#9e8585"

[ui]
bg = "#1c1616"
sidebar_bg = "#221b1b"
panel_bg = "#221b1b"
terminal_bg = "#221b1b"
overlay_bg = "#1c1616D9"
status_bar_bg = "#1c1616"
border_color = "#110d0d"
selection_bg = "#392c2c"

fg = "#caa5a5"
fg_dim = "#ba9b9b"
fg_ghost = "#503939"

accent = "#d35386"
cyan = "#4EAAA4"
magenta = "#A8547A"
amber = "#C48519"
success = "#14b871"
warning = "#cc8c39"
info = "#BA9D6F"
error = "#C13838"

mode_normal = "#d35386"
mode_insert = "#14b871"
mode_visual = "#A8547A"

top_bar_height = 36.0

[git]
modified_sidebar = "#04c4d9"
added_sidebar = "#14b871"
modified_gutter = "#04c4d9"
added_gutter = "#14b871"
deleted_gutter = "#C13838"
status_bar_height = 32.0

[syntax]
keyword = "#C48519"
string = "#639E29"
function = "#BA9D6F"
comment = "#503939"
type = "#BAB13B"
number = "#C13838"
identifier = "#caa5a5"
parameter = "#A8547A"
field = "#caa5a5"
property = "#caa5a5"
constant = "#C13838"
operator = "#C48519"
punctuation = "#caa5a566"
macro = "#BA9D6F"
lifetime = "#D1711D"
boolean = "#C13838"
escape = "#D1711D"
variable = "#D65151"
constructor = "#7E9E2D"
attribute = "#A8547A"
namespace = "#BAB13B"
tag = "#BA9D6F"
keyword_control = "#C48519"
keyword_storage = "#4EAAA4"
string_escape = "#D1711D"
function_builtin = "#BA9D6F"
comment_doc = "#503939"
type_builtin = "#BAB13B"
variable_builtin = "#D65151"
markup_strong = "#D65151"
markup_italic = "#D1711D"
markup_inline_code = "#BAB13B"
markup_link = "#BA9D6F"

