[theme]
name = "bearded-feat-mintshake-d-raynh"
description = "Bearded Theme feat. Mintshake D Raynh palette adapted from JSON/Zed style for Netherize Editor runtime themes"

[editor]
bg = "#f5f5f5"
fg = "#0f212d"
cursor = "#2397e5"
selection = "#e6e6e6"
gutter = "#f5f5f5"
gutter_active = "#696969"

[ui]
bg = "#ececec"
sidebar_bg = "#f5f5f5"
panel_bg = "#f5f5f5"
terminal_bg = "#f5f5f5"
overlay_bg = "#ecececD9"
status_bar_bg = "#ececec"
border_color = "#cfcfcf"
selection_bg = "#d3d3d3"

fg = "#0f212d"
fg_dim = "#000000"
fg_ghost = "#b5b5b5"

accent = "#2397e5"
cyan = "#009c8f"
magenta = "#002e74"
amber = "#d0a00f"
success = "#03810d"
warning = "#c0571f"
info = "#037ed1"
error = "#f7775a"

mode_normal = "#2397e5"
mode_insert = "#03810d"
mode_visual = "#002e74"

top_bar_height = 36.0

[git]
modified_sidebar = "#037ed1"
added_sidebar = "#03810d"
modified_gutter = "#037ed1"
added_gutter = "#03810d"
deleted_gutter = "#f7775a"
status_bar_height = 32.0

[syntax]
keyword = "#d0a00f"
string = "#03810d"
function = "#037ed1"
comment = "#7197b0"
type = "#7537d7"
number = "#f7775a"
identifier = "#0f212d"
parameter = "#002e74"
field = "#0f212d"
property = "#0f212d"
constant = "#f7775a"
operator = "#d0a00f"
punctuation = "#0f212d66"
macro = "#037ed1"
lifetime = "#c0571f"
boolean = "#f7775a"
escape = "#c0571f"
variable = "#1da90d"
constructor = "#75b138"
attribute = "#002e74"
namespace = "#7537d7"
tag = "#037ed1"
keyword_control = "#d0a00f"
keyword_storage = "#009c8f"
string_escape = "#c0571f"
function_builtin = "#037ed1"
comment_doc = "#7197b0"
type_builtin = "#7537d7"
variable_builtin = "#1da90d"
markup_strong = "#1da90d"
markup_italic = "#c0571f"
markup_inline_code = "#7537d7"
markup_link = "#037ed1"

