[theme]
name = "bearded-light"
description = "Bearded Theme Light palette adapted from JSON/Zed style for Netherize Editor runtime themes"

[editor]
bg = "#f3f4f5"
fg = "#091316"
cursor = "#22a5c9"
selection = "#e2e5e7"
gutter = "#f3f4f5"
gutter_active = "#5e6971"

[ui]
bg = "#e9ebed"
sidebar_bg = "#f3f4f5"
panel_bg = "#f3f4f5"
terminal_bg = "#f3f4f5"
overlay_bg = "#e9ebedD9"
status_bar_bg = "#e9ebed"
border_color = "#c9ced2"
selection_bg = "#cdd2d6"

fg = "#091316"
fg_dim = "#000000"
fg_ghost = "#adb5bb"

accent = "#22a5c9"
cyan = "#009999"
magenta = "#e022b4"
amber = "#bb9600"
success = "#14852a"
warning = "#bc7400"
info = "#0073d1"
error = "#ac2121"

mode_normal = "#22a5c9"
mode_insert = "#14852a"
mode_visual = "#e022b4"

top_bar_height = 36.0

[git]
modified_sidebar = "#0468bf"
added_sidebar = "#14852a"
modified_gutter = "#0468bf"
added_gutter = "#14852a"
deleted_gutter = "#ac2121"
status_bar_height = 32.0

[syntax]
keyword = "#bb9600"
string = "#189433"
function = "#0073d1"
comment = "#68919c"
type = "#8737e6"
number = "#d03333"
identifier = "#091316"
parameter = "#e022b4"
field = "#091316"
property = "#091316"
constant = "#d03333"
operator = "#bb9600"
punctuation = "#09131666"
macro = "#0073d1"
lifetime = "#d06200"
boolean = "#d03333"
escape = "#d06200"
variable = "#e8386a"
constructor = "#5e8516"
attribute = "#e022b4"
namespace = "#8737e6"
tag = "#0073d1"
keyword_control = "#bb9600"
keyword_storage = "#009999"
string_escape = "#d06200"
function_builtin = "#0073d1"
comment_doc = "#68919c"
type_builtin = "#8737e6"
variable_builtin = "#e8386a"
markup_strong = "#e8386a"
markup_italic = "#d06200"
markup_inline_code = "#8737e6"
markup_link = "#0073d1"

