[theme]
name = "bearded-vivid-light"
description = "Bearded Theme Vivid Light palette adapted from JSON/Zed style for Netherize Editor runtime themes"

[editor]
bg = "#f4f4f4"
fg = "#181818"
cursor = "#7e7e7e"
selection = "#e5e5e5"
gutter = "#f4f4f4"
gutter_active = "#686868"

[ui]
bg = "#ebebeb"
sidebar_bg = "#f4f4f4"
panel_bg = "#f4f4f4"
terminal_bg = "#f4f4f4"
overlay_bg = "#ebebebD9"
status_bar_bg = "#ebebeb"
border_color = "#cecece"
selection_bg = "#d2d2d2"

fg = "#181818"
fg_dim = "#000000"
fg_ghost = "#b4b4b4"

accent = "#7e7e7e"
cyan = "#00b8a9"
magenta = "#E66DFF"
amber = "#d48700"
success = "#42DD76"
warning = "#FFB638"
info = "#0099ff"
error = "#D62C2C"

mode_normal = "#7e7e7e"
mode_insert = "#42DD76"
mode_visual = "#E66DFF"

top_bar_height = 36.0

[git]
modified_sidebar = "#28A9FF"
added_sidebar = "#42DD76"
modified_gutter = "#28A9FF"
added_gutter = "#42DD76"
deleted_gutter = "#D62C2C"
status_bar_height = 32.0

[syntax]
keyword = "#d48700"
string = "#00ac39"
function = "#0099ff"
comment = "#8a8a8a"
type = "#9c45ff"
number = "#D62C2C"
identifier = "#181818"
parameter = "#E66DFF"
field = "#181818"
property = "#181818"
constant = "#D62C2C"
operator = "#d48700"
punctuation = "#18181866"
macro = "#0099ff"
lifetime = "#df6800"
boolean = "#D62C2C"
escape = "#df6800"
variable = "#ff0062"
constructor = "#6f9b00"
attribute = "#E66DFF"
namespace = "#9c45ff"
tag = "#0099ff"
keyword_control = "#d48700"
keyword_storage = "#00b8a9"
string_escape = "#df6800"
function_builtin = "#0099ff"
comment_doc = "#8a8a8a"
type_builtin = "#9c45ff"
variable_builtin = "#ff0062"
markup_strong = "#ff0062"
markup_italic = "#df6800"
markup_inline_code = "#9c45ff"
markup_link = "#0099ff"

