[theme]
name = "bearded-milkshake-mango"
description = "Bearded Theme Milkshake Mango palette adapted from JSON/Zed style for Netherize Editor runtime themes"

[editor]
bg = "#f3eae3"
fg = "#100a08"
cursor = "#bd4f27"
selection = "#eadace"
gutter = "#f3eae3"
gutter_active = "#845a39"

[ui]
bg = "#eee1d7"
sidebar_bg = "#f3eae3"
panel_bg = "#f3eae3"
terminal_bg = "#f3eae3"
overlay_bg = "#eee1d7D9"
status_bar_bg = "#eee1d7"
border_color = "#dcc2ad"
selection_bg = "#dfc6b3"

fg = "#100a08"
fg_dim = "#000000"
fg_ghost = "#cda789"

accent = "#bd4f27"
cyan = "#008f8f"
magenta = "#c121a4"
amber = "#c08403"
success = "#008b17"
warning = "#c08403"
info = "#0076c5"
error = "#d12525"

mode_normal = "#bd4f27"
mode_insert = "#008b17"
mode_visual = "#c121a4"

top_bar_height = 36.0

[git]
modified_sidebar = "#0076c5"
added_sidebar = "#008b17"
modified_gutter = "#0076c5"
added_gutter = "#008b17"
deleted_gutter = "#d12525"
status_bar_height = 32.0

[syntax]
keyword = "#c08403"
string = "#008b17"
function = "#0076c5"
comment = "#93756a"
type = "#7522d3"
number = "#d12525"
identifier = "#100a08"
parameter = "#c121a4"
field = "#100a08"
property = "#100a08"
constant = "#d12525"
operator = "#c08403"
punctuation = "#100a08"
macro = "#0076c5"
lifetime = "#b96000"
boolean = "#d12525"
escape = "#b96000"
variable = "#da2a5f"
constructor = "#668b07"
attribute = "#c121a4"
namespace = "#7522d3"
tag = "#0076c5"
keyword_control = "#c08403"
keyword_storage = "#008f8f"
string_escape = "#b96000"
function_builtin = "#0076c5"
comment_doc = "#93756a"
type_builtin = "#7522d3"
variable_builtin = "#da2a5f"
markup_strong = "#da2a5f"
markup_italic = "#b96000"
markup_inline_code = "#7522d3"
markup_link = "#0076c5"

