[theme]
name = "bearded-coffee-cream"
description = "Bearded Theme Coffee Cream palette adapted from JSON/Zed style for Netherize Editor runtime themes"

[editor]
bg = "#EAE4E1"
fg = "#36221d"
cursor = "#D3694C"
selection = "#ddd4cf"
gutter = "#EAE4E1"
gutter_active = "#6a5349"

[ui]
bg = "#e3dbd7"
sidebar_bg = "#EAE4E1"
panel_bg = "#EAE4E1"
terminal_bg = "#EAE4E1"
overlay_bg = "#e3dbd7D9"
status_bar_bg = "#e3dbd7"
border_color = "#cbbbb4"
selection_bg = "#cec0b9"

fg = "#36221d"
fg_dim = "#000000"
fg_ghost = "#b6a096"

accent = "#D3694C"
cyan = "#009b74"
magenta = "#CE4985"
amber = "#ad8200"
success = "#51A200"
warning = "#ce6700"
info = "#008ea4"
error = "#FF3A3A"

mode_normal = "#D3694C"
mode_insert = "#51A200"
mode_visual = "#CE4985"

top_bar_height = 36.0

[git]
modified_sidebar = "#009DB5"
added_sidebar = "#51A200"
modified_gutter = "#009DB5"
added_gutter = "#51A200"
deleted_gutter = "#FF3A3A"
status_bar_height = 32.0

[syntax]
keyword = "#ad8200"
string = "#4d9900"
function = "#008ea4"
comment = "#a69692"
type = "#7056c4"
number = "#dc2e2e"
identifier = "#36221d"
parameter = "#CE4985"
field = "#36221d"
property = "#36221d"
constant = "#dc2e2e"
operator = "#ad8200"
punctuation = "#36221d66"
macro = "#008ea4"
lifetime = "#ce6700"
boolean = "#dc2e2e"
escape = "#ce6700"
variable = "#D8573E"
constructor = "#6f8e20"
attribute = "#CE4985"
namespace = "#7056c4"
tag = "#008ea4"
keyword_control = "#ad8200"
keyword_storage = "#009b74"
string_escape = "#ce6700"
function_builtin = "#008ea4"
comment_doc = "#a69692"
type_builtin = "#7056c4"
variable_builtin = "#D8573E"
markup_strong = "#D8573E"
markup_italic = "#ce6700"
markup_inline_code = "#7056c4"
markup_link = "#008ea4"

