[theme]
name = "gruvbox_soft"
description = "Warm retro soft theme for Netherize Editor"

[editor]
bg = "#282828"
fg = "#EBDBB2"
cursor = "#FABD2F"
selection = "#3C3836"
gutter = "#282828"
gutter_active = "#EBDBB2"

[ui]
bg = "#1D2021"
sidebar_bg = "#282828"
panel_bg = "#282828"
terminal_bg = "#141414"
overlay_bg = "#1D2021D9"
status_bar_bg = "#282828"
border_color = "#504945"
selection_bg = "#665C54"

fg = "#EBDBB2"
fg_dim = "#A89984"
fg_ghost = "#7C6F64"

accent = "#D79921"
cyan = "#83A598"
magenta = "#D3869B"
amber = "#FABD2F"
success = "#B8BB26"
warning = "#FE8019"
info = "#83A598"
error = "#FB4934"

mode_normal = "#83A598"
mode_insert = "#B8BB26"
mode_visual = "#D3869B"


top_bar_height = 36.0

[git]
modified_sidebar = "#FABD2F"
added_sidebar = "#B8BB26"
modified_gutter = "#FABD2F"
added_gutter = "#B8BB26"
deleted_gutter = "#FB4934"
status_bar_height = 32.0


[syntax]
keyword = "#FB4934"
string = "#B8BB26"
function = "#FABD2F"
comment = "#928374"
type = "#83A598"
number = "#D3869B"
identifier = "#EBDBB2"
parameter = "#FE8019"
field = "#83A598"
property = "#83A598"
constant = "#D3869B"
operator = "#FE8019"
punctuation = "#EBDBB2"
macro = "#8EC07C"
lifetime = "#FE8019"
boolean = "#D3869B"
escape = "#FE8019"
variable = "#EBDBB2"
constructor = "#FABD2F"
attribute = "#D79921"
namespace = "#83A598"
tag = "#FB4934"
