#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INPUT_DIR="${ROOT_DIR}/benchmarks/inputs"
RUST_10K_FILE="${INPUT_DIR}/rust_10k_lines.rs"
LOG_50MB_FILE="${INPUT_DIR}/log_50mb.txt"
TARGET_LOG_SIZE_BYTES=$((50 * 1024 * 1024))

mkdir -p "${INPUT_DIR}"

echo "[Perf Samples] generating ${RUST_10K_FILE}"
{
  echo "// Generated by scripts/generate_bench_samples.sh"
  echo "pub fn bench_generated_lines() {"
  for i in $(seq 1 10000); do
    printf "    let value_%05d = %d;\n" "${i}" "${i}"
  done
  echo "    println!(\"{}\", value_10000);"
  echo "}"
} > "${RUST_10K_FILE}"

echo "[Perf Samples] generating ${LOG_50MB_FILE} (~50MB text payload)"
LOG_LINE='2026-04-19T00:00:00Z level=INFO module=bench userId=12345 fps=120 rtt=42 jitter=2 loss=0 message="synthetic benchmark log line for netherize editor perf kit"'
# Temporarily disable pipefail to avoid SIGPIPE (141) from `yes` when `head` exits early.
set +o pipefail
yes "${LOG_LINE}" | head -c "${TARGET_LOG_SIZE_BYTES}" > "${LOG_50MB_FILE}"
set -o pipefail

echo "[Perf Samples] done"
wc -c "${RUST_10K_FILE}" "${LOG_50MB_FILE}"
